print("=" * 55)
print("           PERSONAL PORTFOLIO")
print("=" * 55)

print("\nPERSONAL INFORMATION")
print("---------------------")
print("Name           : Aarya Agarwal")
print("Register No.   : 24mis0145")
print("Department     : Computer Science and Engineering")
print("College        : VIT Vellore")

print("\nEDUCATION")
print("---------------------")
print("• B.Tech - Computer Science and Engineering")
print("• VIT Vellore")

print("\nSKILLS")
print("---------------------")
print("• Python")
print("• Git & GitHub")
print("• Canva")
print("• Figma")
print("• HTML & CSS")
print("• SQL")

print("\nPROJECTS")
print("---------------------")
print("• Student Information System")
print("• Mini Calculator")
print("• Number Analyzer")
print("• Banking System")
print("• Guess the Number Game")
print("• Library Management System")

print("\nHOBBIES")
print("---------------------")
print("• Graphic Designing")
print("• Video Editing")
print("• Reading")
print("• Photography")

print("\nCONTACT")
print("---------------------")
print("Email : aarya.2024@vitstudent.ac.in")
print("GitHub: https://github.com/aarya2024-afk")

print("\n" + "=" * 55)
print("      THANK YOU FOR VISITING MY PORTFOLIO")
print("=" * 55)